networks:
  deploy-rindo:
    driver: bridge
services:
  rindo.api:
    image: rindo.api
    build:
      context: .
      dockerfile: Rindo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtOptions__SecretKey=secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
      - ConnectionStrings__Database=Server=rindo.db;Database=rindoDb;Port=5432;User ID=postgres;Password=123;
    ports:
      - "5000:80"
    networks:
      - deploy-rindo
    depends_on:
      - rindo.db
  
  rindo.db:
    image: postgres:latest
    restart: always
    container_name: rindo.db
    environment:
      - POSTGRES_DB=rindoDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - /rindo-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - deploy-rindo
  
  client:
    image: client
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
  
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
volumes:
  rindo-db: